USE [master]
GO
/****** Object:  Database [DBproductos]    Script Date: 23/7/2020 11:55:21 p. m. ******/
CREATE DATABASE [DBproductos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDproductos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BDproductos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDproductos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BDproductos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DBproductos] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBproductos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBproductos] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBproductos] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBproductos] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBproductos] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBproductos] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBproductos] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBproductos] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBproductos] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBproductos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBproductos] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBproductos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBproductos] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBproductos] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBproductos] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBproductos] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBproductos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBproductos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBproductos] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBproductos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBproductos] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBproductos] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBproductos] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBproductos] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBproductos] SET  MULTI_USER 
GO
ALTER DATABASE [DBproductos] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBproductos] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBproductos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBproductos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBproductos] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBproductos] SET QUERY_STORE = OFF
GO
USE [DBproductos]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 23/7/2020 11:55:21 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nchar](10) NOT NULL,
	[Detalle] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 23/7/2020 11:55:21 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Precio] [decimal](18, 0) NOT NULL,
	[Detalle] [nvarchar](50) NOT NULL,
	[Id_Categoria] [int] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 23/7/2020 11:55:21 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Correo] [nchar](50) NOT NULL,
	[Contrasena] [nchar](20) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Categoria] FOREIGN KEY([Id_Categoria])
REFERENCES [dbo].[Categoria] ([Id])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Categoria]
GO
USE [master]
GO
ALTER DATABASE [DBproductos] SET  READ_WRITE 
GO
